FROM ethznetsec/scion_base:latest

ARG SCION_SRC
ARG SC
ARG JACKAL_DIR

# Update
RUN sudo apt-get update && sudo apt-get install --assume-yes libpcap0.8 libpcap0.8-dev

# Checkout SCION
RUN git clone ${SCION_SRC} -b scionlab --depth 1 ${SC}

RUN sudo apt-get update && sudo apt-get install --assume-yes apt-transport-https
RUN sudo bash -c 'echo "deb [trusted=yes] https://packages.netsec.inf.ethz.ch/debian all main" >> /etc/apt/sources.list'
RUN sudo apt-get update && sudo apt-get install --assume-yes scionlab

COPY ./setup/loadASConfig.sh ${SC}/loadASConfig.sh
RUN sudo mkdir -p /var/log/scion/
RUN mkdir ${SC}/gen-cache

# install jackal dependencies
COPY ./setup/install_jackal.sh ${SC}/install_jackal.sh
RUN ./install_jackal.sh

# Add environment variables for execution
ENV PYTHONPATH ${SC}/python
ENV JACKAL_DIR ${JACKAL_DIR}
ENV SC ${SC}
