FROM ethznetsec/scion_base:latest

ARG SCION_SRC
ARG SC
ARG JACKAL
ARG JACKAL_ID

# Update
RUN sudo apt-get update && sudo apt-get install --assume-yes libpcap0.8 libpcap0.8-dev

# Install SCION
RUN git clone ${SCION_SRC} -b scionlab --depth 1 ${SC}

RUN cd ${SC} && ./env/deps

RUN cd ${SC} && make
## To be replaced by the package installation

COPY ./setup/loadASConfig.sh ${SC}/loadASConfig.sh
COPY ./setup/share_zk.sh ${SC}/share_zk.sh
RUN mkdir ${SC}/gen-cache

# install jackal dependencies
RUN echo "19-ffaa:0:1303,[127.0.0.1] server1.xmpp." | sudo tee -a /etc/hosts
COPY ./setup/install_jackal.sh ${SC}/install_jackal.sh
RUN ./install_jackal.sh

# Add environment variables for execution
ENV PYTHONPATH ${SC}/python
ENV SC ${SC}
